"""AI Cost Optimization & Provider Intelligence Engine versioning."""

ENGINE_NAME = "RTAS AI Cost Optimization & Provider Intelligence Engine"
ENGINE_VERSION = "1.0.0"
ENGINE_LABEL = f"{ENGINE_NAME} v{ENGINE_VERSION}"
PHASE = 6
SPRINT = 5

DEFAULT_DAILY_BUDGET_USD = 50.0
DEFAULT_MONTHLY_BUDGET_USD = 1000.0
OPTIMIZATION_COST_WEIGHT = 0.35
OPTIMIZATION_SPEED_WEIGHT = 0.20
OPTIMIZATION_QUALITY_WEIGHT = 0.20
OPTIMIZATION_RELIABILITY_WEIGHT = 0.25
