/**
 * Phase 13 Sprint 9 — Marketing Campaign Center plans.
 * Structures only. Metrics are intentionally non-numeric / Ready for Integration.
 */

import type { CampaignPlan } from "./types";

export const CAMPAIGN_PLANS: CampaignPlan[] = [
  {
    id: "yt-product-story",
    channel: "youtube",
    name: "YouTube — Product story & demos",
    objective: "Show compose → render → publish with Authorized Identity Preservation.",
    audience: "Creators, editors, agency producers researching AI video tools.",
    contentPillars: [
      "Studio walkthrough (real UI)",
      "Credit economics explained (1 credit = 1 second)",
      "Identity Preservation policy (authorized-only)",
      "Before/after craft clips from /showcase when assets exist",
    ],
    status: "planned",
    metricsNote: "Ready for Integration — connect YouTube Analytics; do not invent views.",
    assetsNeeded: ["Demo screen capture", "Logo end-card", "Captions"],
    owner: "marketing",
    cta: "https://rtasstudio.com/auth/signup",
  },
  {
    id: "li-b2b",
    channel: "linkedin",
    name: "LinkedIn — B2B & agency GTM",
    objective: "Reach marketing leads and creative directors with enterprise-honest messaging.",
    audience: "Agency owners, brand marketers, production leads.",
    contentPillars: [
      "ICP problem framing (speed + identity trust)",
      "Pricing transparency posts",
      "Founder notes (operator-built inside RTAS Digital Marketing Company)",
      "Enterprise / demo CTA",
    ],
    status: "in_progress",
    metricsNote: "Ready for Integration — LinkedIn Campaign Manager / organic insights.",
    assetsNeeded: ["Square brand stills", "Founder headshot (placeholder until real)", "Case narrative (no fake logos)"],
    owner: "marketing",
    cta: "https://rtasstudio.com/enterprise",
  },
  {
    id: "x-launch",
    channel: "x",
    name: "X — Launch thread & updates",
    objective: "Ship candid launch updates; drive to pricing and signup.",
    audience: "AI builders, creators, indie hackers.",
    contentPillars: ["Launch day thread", "Changelog highlights", "Support / status honesty"],
    status: "planned",
    metricsNote: "Ready for Integration — X Analytics; zero impressions until posted.",
    assetsNeeded: ["Thread outline", "OG image"],
    owner: "marketing",
    cta: "https://rtasstudio.com/",
  },
  {
    id: "fb-community",
    channel: "facebook",
    name: "Facebook — Community & retargeting prep",
    objective: "Warm audiences and creative tests once Meta pixel is live.",
    audience: "Creator communities and lookalikes (after real seed events).",
    contentPillars: ["Short demo cuts", "Credit clarity creatives", "Retargeting to /pricing"],
    status: "planned",
    metricsNote: "Ready for Integration — Meta Ads Manager; no fabricated reach.",
    assetsNeeded: ["Vertical creatives", "Pixel / CAPI wiring"],
    owner: "marketing",
    cta: "https://rtasstudio.com/pricing",
  },
  {
    id: "ig-visual",
    channel: "instagram",
    name: "Instagram — Visual craft feed",
    objective: "Build brand recognition with craft-led stills and Reels.",
    audience: "Visual creators and music-video audiences.",
    contentPillars: ["Reel demos", "Carousel: how credits work", "Stories → link in bio"],
    status: "planned",
    metricsNote: "Ready for Integration — Instagram Insights.",
    assetsNeeded: ["9:16 clips", "Brand color stills"],
    owner: "marketing",
    cta: "https://rtasstudio.com/showcase",
  },
  {
    id: "tt-short",
    channel: "tiktok",
    name: "TikTok — Short-form demos",
    objective: "Hook with real generation progress UI; avoid deepfake tropes.",
    audience: "Short-form creators evaluating AI video.",
    contentPillars: ["15s Studio hooks", "Identity policy callouts", "Tester plan tease ($5)"],
    status: "planned",
    metricsNote: "Ready for Integration — TikTok Analytics.",
    assetsNeeded: ["Raw screen recordings", "Caption templates"],
    owner: "marketing",
    cta: "https://rtasstudio.com/auth/signup",
  },
  {
    id: "reddit-ama",
    channel: "reddit",
    name: "Reddit — Authentic participation",
    objective: "Answer honestly in relevant subs; no spam or fake testimonials.",
    audience: "r/artificial, filmmaking, SaaS, and related communities (policy-compliant).",
    contentPillars: ["AMA outline", "Limitation honesty", "Helpful how-tos"],
    status: "planned",
    metricsNote: "Manual tracking only — do not invent upvotes.",
    assetsNeeded: ["Founder bio", "Known limitations one-pager"],
    owner: "founder",
    cta: "https://rtasstudio.com/feedback",
  },
  {
    id: "ph-launch",
    channel: "product_hunt",
    name: "Product Hunt — Launch day",
    objective: "Coordinate hunter, gallery, and first-comment assets.",
    audience: "PH makers and early adopters.",
    contentPillars: ["Tagline (Authorized Identity Preservation)", "Gallery images", "Maker comment FAQ"],
    status: "planned",
    metricsNote: "No fabricated ranking — report only after a real launch day.",
    assetsNeeded: ["PH gallery (1270×760)", "Logo mark", "GIF demo"],
    owner: "marketing",
    cta: "https://rtasstudio.com/",
  },
  {
    id: "gads-search",
    channel: "google_ads",
    name: "Google Ads — Search (brand + category)",
    objective: "Capture high-intent queries once conversion tracking is verified.",
    audience: "Searchers for AI video studio / commercial AI video.",
    contentPillars: ["Brand exact", "Category broad (tight negatives)", "Competitor conquest (ethical)"],
    status: "not_started",
    metricsNote: "Ready for Integration — Google Ads + GA4; spend = $0 until account live.",
    assetsNeeded: ["RSA copy variants", "Conversion events verified"],
    owner: "marketing",
    cta: "https://rtasstudio.com/pricing",
  },
  {
    id: "meta-ads",
    channel: "meta_ads",
    name: "Meta Ads — Prospecting & retargeting",
    objective: "Test creatives only after pixel + purchase events are real.",
    audience: "Interest + lookalike after real conversion seed (not invented).",
    contentPillars: ["Tester $5 offer", "Standard plan value", "Retarget abandon signup"],
    status: "not_started",
    metricsNote: "Ready for Integration — Meta Ads Manager; no fake CTR/ROAS.",
    assetsNeeded: ["Primary text variants", "Pixel events"],
    owner: "marketing",
    cta: "https://rtasstudio.com/auth/signup",
  },
];

export const CAMPAIGN_CHANNEL_LABEL: Record<CampaignPlan["channel"], string> = {
  youtube: "YouTube",
  linkedin: "LinkedIn",
  x: "X",
  facebook: "Facebook",
  instagram: "Instagram",
  tiktok: "TikTok",
  reddit: "Reddit",
  product_hunt: "Product Hunt",
  google_ads: "Google Ads",
  meta_ads: "Meta Ads",
};
