"""Platform export presets."""

from __future__ import annotations

from typing import Any

from app.services.audio_export.models import ExportProfile

_PROFILES: dict[str, ExportProfile] = {
    "youtube": ExportProfile(
        profile_id="youtube",
        platform="youtube",
        label="YouTube",
        video_format="mp4",
        audio_format="aac",
        resolution="1920x1080",
        width=1920,
        height=1080,
        video_bitrate_kbps=8000,
        audio_bitrate_kbps=320,
        audio_loudness_lufs=-14.0,
        video_codec="h264",
        audio_codec="aac",
        fps=30.0,
        aspect_ratio="16:9",
    ),
    "youtube_shorts": ExportProfile(
        profile_id="youtube_shorts",
        platform="youtube_shorts",
        label="YouTube Shorts",
        video_format="mp4",
        audio_format="aac",
        resolution="1080x1920",
        width=1080,
        height=1920,
        video_bitrate_kbps=6000,
        audio_bitrate_kbps=192,
        audio_loudness_lufs=-14.0,
        video_codec="h264",
        audio_codec="aac",
        fps=30.0,
        aspect_ratio="9:16",
        max_duration_sec=60.0,
    ),
    "tiktok": ExportProfile(
        profile_id="tiktok",
        platform="tiktok",
        label="TikTok",
        video_format="mp4",
        audio_format="aac",
        resolution="1080x1920",
        width=1080,
        height=1920,
        video_bitrate_kbps=6000,
        audio_bitrate_kbps=192,
        audio_loudness_lufs=-14.0,
        video_codec="h264",
        audio_codec="aac",
        fps=30.0,
        aspect_ratio="9:16",
        max_duration_sec=180.0,
    ),
    "instagram_reels": ExportProfile(
        profile_id="instagram_reels",
        platform="instagram_reels",
        label="Instagram Reels",
        video_format="mp4",
        audio_format="aac",
        resolution="1080x1920",
        width=1080,
        height=1920,
        video_bitrate_kbps=5500,
        audio_bitrate_kbps=192,
        audio_loudness_lufs=-14.0,
        video_codec="h264",
        audio_codec="aac",
        fps=30.0,
        aspect_ratio="9:16",
        max_duration_sec=90.0,
    ),
    "facebook": ExportProfile(
        profile_id="facebook",
        platform="facebook",
        label="Facebook",
        video_format="mp4",
        audio_format="aac",
        resolution="1280x720",
        width=1280,
        height=720,
        video_bitrate_kbps=4000,
        audio_bitrate_kbps=192,
        audio_loudness_lufs=-16.0,
        video_codec="h264",
        audio_codec="aac",
        fps=30.0,
        aspect_ratio="16:9",
    ),
    "linkedin": ExportProfile(
        profile_id="linkedin",
        platform="linkedin",
        label="LinkedIn",
        video_format="mp4",
        audio_format="aac",
        resolution="1920x1080",
        width=1920,
        height=1080,
        video_bitrate_kbps=5000,
        audio_bitrate_kbps=192,
        audio_loudness_lufs=-16.0,
        video_codec="h264",
        audio_codec="aac",
        fps=30.0,
        aspect_ratio="16:9",
    ),
    "x_twitter": ExportProfile(
        profile_id="x_twitter",
        platform="x_twitter",
        label="X (Twitter)",
        video_format="mp4",
        audio_format="aac",
        resolution="1280x720",
        width=1280,
        height=720,
        video_bitrate_kbps=5000,
        audio_bitrate_kbps=192,
        audio_loudness_lufs=-16.0,
        video_codec="h264",
        audio_codec="aac",
        fps=30.0,
        aspect_ratio="16:9",
        max_duration_sec=140.0,
    ),
    "snapchat": ExportProfile(
        profile_id="snapchat",
        platform="snapchat",
        label="Snapchat",
        video_format="mp4",
        audio_format="aac",
        resolution="1080x1920",
        width=1080,
        height=1920,
        video_bitrate_kbps=5000,
        audio_bitrate_kbps=192,
        audio_loudness_lufs=-14.0,
        video_codec="h264",
        audio_codec="aac",
        fps=30.0,
        aspect_ratio="9:16",
        max_duration_sec=60.0,
    ),
    "website": ExportProfile(
        profile_id="website",
        platform="website",
        label="Website",
        video_format="webm",
        audio_format="ogg",
        resolution="1920x1080",
        width=1920,
        height=1080,
        video_bitrate_kbps=4500,
        audio_bitrate_kbps=192,
        audio_loudness_lufs=-16.0,
        video_codec="vp9",
        audio_codec="opus",
        fps=30.0,
        aspect_ratio="16:9",
    ),
    "commercial_broadcast": ExportProfile(
        profile_id="commercial_broadcast",
        platform="commercial_broadcast",
        label="Commercial Broadcast",
        video_format="mov",
        audio_format="wav",
        resolution="3840x2160",
        width=3840,
        height=2160,
        video_bitrate_kbps=50000,
        audio_bitrate_kbps=1536,
        audio_loudness_lufs=-24.0,
        video_codec="prores",
        audio_codec="pcm",
        fps=24.0,
        aspect_ratio="16:9",
        metadata_format="xml",
    ),
}

AUDIO_FORMATS = ("wav", "mp3", "flac", "aac", "ogg")
VIDEO_FORMATS = ("mp4", "mov", "mkv", "webm")
METADATA_FORMATS = ("json", "xml")


def list_profiles() -> list[ExportProfile]:
    return list(_PROFILES.values())


def get_profile(platform: str) -> ExportProfile | None:
    key = (platform or "").strip().lower().replace(" ", "_").replace("-", "_")
    aliases = {
        "twitter": "x_twitter",
        "x": "x_twitter",
        "instagram": "instagram_reels",
        "reels": "instagram_reels",
        "shorts": "youtube_shorts",
        "broadcast": "commercial_broadcast",
        "commercial": "commercial_broadcast",
    }
    key = aliases.get(key, key)
    return _PROFILES.get(key)


def profiles_payload() -> dict[str, Any]:
    return {
        "profiles": [p.to_dict() for p in list_profiles()],
        "audio_formats": list(AUDIO_FORMATS),
        "video_formats": list(VIDEO_FORMATS),
        "metadata_formats": list(METADATA_FORMATS),
        "count": len(_PROFILES),
    }
