"""Multi-Tenant SaaS Platform Foundation versioning."""

ENGINE_NAME = "RTAS Multi-Tenant SaaS Foundation"
ENGINE_VERSION = "1.0.0"
ENGINE_LABEL = f"{ENGINE_NAME} v{ENGINE_VERSION}"
PHASE = 7
SPRINT = 1

MAX_ORGS_PER_OWNER = 100
MAX_WORKSPACES_PER_ORG = 200
MAX_TEAMS_PER_ORG = 500
MAX_MEMBERS_PER_ORG = 5000
MAX_INVITES_PER_ORG = 2000
DEFAULT_INVITE_TTL_HOURS = 72
