"""AI Memory, Context & Knowledge Engine versioning."""

ENGINE_NAME = "RTAS AI Memory, Context & Knowledge Engine"
ENGINE_VERSION = "1.0.0"
ENGINE_LABEL = f"{ENGINE_NAME} v{ENGINE_VERSION}"
PHASE = 6
SPRINT = 6

SHORT_TERM_TTL_SEC = 3600
MAX_MEMORY_RECORDS = 10000
MAX_KNOWLEDGE_RECORDS = 8000
CACHE_TTL_SEC = 120
RETRIEVAL_TOP_K = 20
