from fastapi import APIRouter

from app.api.routes import (
    access,
    admin,
    ai,
    analytics,
    assets,
    audio,
    audio_engine,
    camera,
    camera_motion,
    comms,
    context,
    emotion,
    enterprise_saas,
    generate,
    health,
    image_to_video,
    intelligence,
    invitations,
    jobs,
    knowledge,
    lip_sync,
    localization,
    management,
    memory,
    pipeline,
    timeline,
    export,
    workflow,
    audio_pipeline,
    avatar,
    billing,
    paddle,
    paypal,
    wallet,
    credits,
    costs,
    usage,
    referral_affiliate,
    license_platform,
    provider_analytics,
    marketplace,
    marketplace_ecosystem,
    creator_platform,
    motion,
    motion_intelligence,
    multi_ai,
    providers,
    ai_router,
    multi_gpu,
    music,
    organizations,
    physics,
    platform,
    platform_ops,
    projects,
    scene_render,
    security,
    system,
    teams,
    talking_avatar,
    text_to_video,
    upload,
    version_control,
    video_engine,
    voice,
    workspaces,
    world,
    director,
    download,
    final_release,
)

api_router = APIRouter(prefix="/api")
api_router.include_router(health.router)
api_router.include_router(admin.router)
api_router.include_router(platform_ops.router)
api_router.include_router(enterprise_saas.router)
api_router.include_router(billing.router)
api_router.include_router(paddle.router)
api_router.include_router(paypal.router)
api_router.include_router(wallet.router)
api_router.include_router(credits.router)
api_router.include_router(costs.router)
api_router.include_router(usage.router)
api_router.include_router(referral_affiliate.referrals_router)
api_router.include_router(referral_affiliate.affiliate_router)
api_router.include_router(license_platform.licenses_router)
api_router.include_router(license_platform.developer_router)
api_router.include_router(provider_analytics.analytics_router)
api_router.include_router(provider_analytics.budget_router)
api_router.include_router(provider_analytics.optimization_router)
api_router.include_router(marketplace.marketplace_router)
api_router.include_router(marketplace_ecosystem.ecosystem_router)
api_router.include_router(creator_platform.creator_router)
api_router.include_router(creator_platform.publisher_router)
api_router.include_router(ai.router)
api_router.include_router(upload.router)
api_router.include_router(generate.router)
api_router.include_router(jobs.router)
api_router.include_router(intelligence.router)
api_router.include_router(multi_ai.router)
api_router.include_router(providers.router)
api_router.include_router(ai_router.router)
api_router.include_router(memory.router)
api_router.include_router(context.router)
api_router.include_router(knowledge.router)
api_router.include_router(workflow.router)
api_router.include_router(pipeline.router)
api_router.include_router(security.router)
api_router.include_router(system.router)
api_router.include_router(platform.router)
api_router.include_router(organizations.router)
api_router.include_router(access.router)
api_router.include_router(workspaces.router)
api_router.include_router(teams.router)
api_router.include_router(invitations.router)
api_router.include_router(management.router)
api_router.include_router(projects.router)
api_router.include_router(assets.router)
api_router.include_router(comms.notifications_router)
api_router.include_router(comms.activity_router)
api_router.include_router(comms.comments_router)
api_router.include_router(comms.announcements_router)
api_router.include_router(version_control.versions_router)
api_router.include_router(version_control.reviews_router)
api_router.include_router(version_control.changelog_router)
api_router.include_router(analytics.analytics_router)
api_router.include_router(analytics.reports_router)
api_router.include_router(analytics.kpi_router)
api_router.include_router(text_to_video.router)
api_router.include_router(image_to_video.router)
api_router.include_router(talking_avatar.router)
api_router.include_router(lip_sync.router)
api_router.include_router(motion_intelligence.router)
api_router.include_router(camera_motion.router)
api_router.include_router(physics.router)
api_router.include_router(scene_render.router)
api_router.include_router(multi_gpu.router)
api_router.include_router(video_engine.router)
api_router.include_router(audio_engine.router)
api_router.include_router(audio.router)
api_router.include_router(music.router)
api_router.include_router(localization.router)
api_router.include_router(timeline.router)
api_router.include_router(export.router)
api_router.include_router(audio_pipeline.router)
api_router.include_router(avatar.router)
api_router.include_router(voice.router)
api_router.include_router(motion.router)
api_router.include_router(camera.router)
api_router.include_router(emotion.router)
api_router.include_router(world.router)
api_router.include_router(director.router)
api_router.include_router(download.router)
api_router.include_router(final_release.router)
