/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      colors: {
        ds: {
          bg: "var(--ds-bg)",
          "bg-deep": "var(--ds-bg-deep)",
          surface: "var(--ds-surface)",
          "surface-2": "var(--ds-surface-2)",
          "surface-glass": "var(--ds-surface-glass)",
          border: "var(--ds-border)",
          text: "var(--ds-text)",
          "text-body": "var(--ds-text-body)",
          muted: "var(--ds-text-muted)",
          accent: "var(--ds-accent)",
          "accent-2": "var(--ds-accent-2)",
          lavender: "var(--ds-accent-lavender)",
          "lavender-hover": "var(--ds-accent-lavender-hover)",
          danger: "var(--ds-danger)",
          success: "var(--ds-success)",
          link: "var(--ds-link)",
          card: "var(--ds-card)",
          "card-2": "var(--ds-card-2)",
        },
      },
      fontFamily: {
        sans: ["var(--ds-font-sans)"],
        mono: ["var(--ds-font-mono)"],
      },
      fontSize: {
        xs: ["var(--ds-text-xs)", { lineHeight: "var(--ds-leading-normal)" }],
        sm: ["var(--ds-text-sm)", { lineHeight: "var(--ds-leading-normal)" }],
        base: ["var(--ds-text-base)", { lineHeight: "var(--ds-leading-normal)" }],
        md: ["var(--ds-text-md)", { lineHeight: "var(--ds-leading-normal)" }],
        lg: ["var(--ds-text-lg)", { lineHeight: "var(--ds-leading-snug)" }],
        xl: ["var(--ds-text-xl)", { lineHeight: "var(--ds-leading-snug)" }],
        "2xl": ["var(--ds-text-2xl)", { lineHeight: "var(--ds-leading-tight)" }],
        "3xl": ["var(--ds-text-3xl)", { lineHeight: "var(--ds-leading-tight)" }],
        "4xl": ["var(--ds-text-4xl)", { lineHeight: "var(--ds-leading-tight)" }],
        "5xl": ["var(--ds-text-5xl)", { lineHeight: "var(--ds-leading-tight)" }],
        "6xl": ["var(--ds-text-6xl)", { lineHeight: "var(--ds-leading-tight)" }],
      },
      spacing: {
        0.5: "var(--ds-space-0-5)",
        1: "var(--ds-space-1)",
        1.5: "var(--ds-space-1-5)",
        2: "var(--ds-space-2)",
        2.5: "var(--ds-space-2-5)",
        3: "var(--ds-space-3)",
        3.5: "var(--ds-space-3-5)",
        4: "var(--ds-space-4)",
        5: "var(--ds-space-5)",
        6: "var(--ds-space-6)",
        7: "var(--ds-space-7)",
        8: "var(--ds-space-8)",
        9: "var(--ds-space-9)",
        10: "var(--ds-space-10)",
        11: "var(--ds-space-11)",
        12: "var(--ds-space-12)",
        14: "var(--ds-space-14)",
        16: "var(--ds-space-16)",
        20: "var(--ds-space-20)",
        24: "var(--ds-space-24)",
        32: "var(--ds-space-32)",
      },
      borderRadius: {
        sm: "var(--ds-radius-sm)",
        DEFAULT: "var(--ds-radius-md)",
        md: "var(--ds-radius-md)",
        lg: "var(--ds-radius-lg)",
        xl: "var(--ds-radius-xl)",
        "2xl": "var(--ds-radius-2xl)",
        full: "var(--ds-radius-full)",
      },
      boxShadow: {
        "ds-sm": "var(--ds-shadow-sm)",
        "ds-md": "var(--ds-shadow-md)",
        "ds-lg": "var(--ds-shadow-lg)",
        "ds-xl": "var(--ds-shadow-xl)",
        "ds-2xl": "var(--ds-shadow-2xl)",
        "ds-header": "var(--ds-shadow-header)",
        "ds-panel": "var(--ds-shadow-panel)",
        "ds-glow-purple": "var(--ds-shadow-glow-purple)",
        "ds-glow-gold": "var(--ds-shadow-glow-gold)",
      },
      transitionDuration: {
        fast: "var(--ds-duration-fast)",
        DEFAULT: "var(--ds-duration-normal)",
        slow: "var(--ds-duration-slow)",
        slower: "var(--ds-duration-slower)",
      },
      transitionTimingFunction: {
        DEFAULT: "var(--ds-ease-default)",
        out: "var(--ds-ease-out)",
        spring: "var(--ds-ease-spring)",
        bounce: "var(--ds-ease-bounce)",
      },
      backdropBlur: {
        ds: "var(--ds-blur-md)",
        "ds-lg": "var(--ds-blur-lg)",
        "ds-xl": "var(--ds-blur-xl)",
        "ds-2xl": "var(--ds-blur-2xl)",
      },
    },
  },
};
